"""
Django settings for skateshop project.

Generated by 'django-admin startproject' using Django 5.2.9.
Merged for Render.com deployment (PostgreSQL + Cloudinary + DRF API).
"""

import os
from pathlib import Path
import dj_database_url
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# CONFIGURAÇÕES DE AMBIENTE (LOCAL VS RENDER)
# ==============================================================================

# 1. A chave secreta pega do ambiente ou usa uma padrão insegura (só para dev local)
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-chave-padrao-para-dev")

# 2. Debug é True no seu PC, mas False quando estiver no Render
DEBUG = "RENDER" not in os.environ

# 3. Define quem pode acessar o site
ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# ==============================================================================
# APLICAÇÃO
# ==============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    # Cloudinary deve vir antes do staticfiles (recomendação da lib)
    "cloudinary_storage",
    "cloudinary",
    "django.contrib.staticfiles",
    # Django Rest Framework (Para a API)
    "rest_framework",
    # App da Loja
    "store",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "skateshop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "skateshop.wsgi.application"


# ==============================================================================
# BANCO DE DADOS
# ==============================================================================
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        # Localmente usa SQLite
        default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
        # Mantém a conexão ativa por 10min (melhora performance no Render)
        conn_max_age=600,
    )
}


# ==============================================================================
# VALIDAÇÃO DE SENHA E I18N
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ==============================================================================
# ARQUIVOS ESTÁTICOS (CSS, JS) - WHITENOISE
# ==============================================================================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ==============================================================================
# ARQUIVOS DE MÍDIA (UPLOADS) - CLOUDINARY
# ==============================================================================

# URL pública para acessar arquivos de mídia
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Configuração do Cloudinary
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.environ.get("CLOUDINARY_API_KEY"),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET"),
}

# LÓGICA DE FORÇA BRUTA:
# Se estiver no Render, TEM que usar Cloudinary.
# Se estiver local mas tiver as chaves no .env, também usa.
if "RENDER" in os.environ or os.environ.get("CLOUDINARY_API_KEY"):
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
    print(f" MODO CLOUDINARY ATIVADO: {os.environ.get('CLOUDINARY_CLOUD_NAME')}")
else:
    # Apenas para desenvolvimento local sem internet/chaves
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    print(" MODO ARQUIVO LOCAL (As imagens vão sumir no Render!)")

# Debug simples para saber qual banco está rodando nos logs
try:
    from django.db import connection

    print(f" BANCO EM USO: {connection.vendor}")
except:
    pass
